#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# ---------------------------------------------------------------------------- #
#                                 Code updates                                 #
# ---------------------------------------------------------------------------- #

# -------------------------- Foundry code formatting ------------------------- #

# forge fmt

# ------------------------ Precompute Solidity Hashes ------------------------ #

npx ts-node scripts/precompute-solidity-hashes.ts

# --------------------------- Add any changes made --------------------------- #

git add .